language: fortran
sudo: required
cache:
    apt: true
addons:
    apt:
        packages:
            - gfortran-6
            - cmake
            - libopenblas-dev
            - liblapack-dev

before_install:
  - sudo apt-get

script:
- export FC=gfortran
- git submodule init
- git submodule update
- mkdir thirdParty/pfunit/mod
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=DEBUG ..
- make

after_success:
  - bash <(curl -s https://codecov.io/bash)
